### ISSUE TITLE
Enable the LMP docs website

### ISSUE THREAD

**Issue by yunwei37** [linuxkerneltravel/lmp_docs#1]
First, we need to enable the github pages for this repo here:

![image](https://user-images.githubusercontent.com/34985212/195967966-57fac9f7-91a5-4f75-80b1-68935d4976ca.png)

And you may need to use Event Triggering by other repository, run CI when someone push to LMP, or run at a schedule

ref:
- https://github.com/orgs/community/discussions/26323
- https://stackoverflow.com/questions/65370859/github-action-trigger-on-another-repo-update-push-pull-request

**Comment by helight** [comment]
done
